version: "3"
services:
  hugo:
    image: docker.io/klakegg/hugo:${HUGO_VERSION}-ext
    container_name: cocodev-org
    hostname: cocodev-org
    restart: unless-stopped
    command:
      - server
      - --buildFuture
      - --disableFastRender
      - --verbose
      - --port=1313
      - --liveReloadPort=26263
    volumes:
      - .:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports: [ "26263:1313", ]
