#!/usr/bin/env bash

arg=${1:-up}

case $arg in
    "setup")
        git submodule update --init --recursive
        docker-compose exec hugo /src/update
        ;;
    "up")
        docker-compose up
        docker-compose down
        ;;
    "new")
        docker-compose exec hugo hugo new "${@:2}"
        ;;
    "down")
        docker-compose down
        ;;
    "update")
        docker-compose exec hugo /src/update
        ;;
    "restart")
        docker-compose down
        docker-compose up -d
        ;;
esac
